Name: Go CI/CD

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Install dependencies
      run: go mod tidy

    - name: Start PostgreSQL
      run: docker compose up -d postgres

    - name: Wait for PostgreSQL
      run: |
        echo "Waiting for PostgreSQL..."
        sleep 10
        docker compose logs postgres

    - name: Start App
      run: docker compose up -d app

    - name: Verify running containers
      run: docker compose ps

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.59
        args: ./...

    - name: Check Docker logs
      run: docker compose logs

    - name: Run Tests
      run: docker compose exec -T app go test -v ./...

    - name: Stop services
      run: docker compose down
