# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: go mod tidy

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Inicia banco
      run: docker compose up -d postgres

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
          version: v1.59 
          args: controllers/ database/ models/ routes/

    - name: Check Docker logs
      run: echo "Exibindo logs do Docker..." && docker compose logs

    - name: Test
      run: docker compose exec app go test ./...

