name: Go

on:
  push:
    branches: [ '*']
  pull_request:
    branches: [ '* ']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: go mod tidy

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        
    - name: Inicia banco
      run: docker compose up -d postgres

    - name: Aguarda o banco estar pronto
      run: |
        echo "Aguardando PostgreSQL iniciar..."
        sleep 10
        docker compose logs postgres

    - name: Inicia aplicação
      run: sudo docker compose up -d app  # Garante que o serviço "app" está rodando

    - name: Verificar serviços ativos
      run: docker compose ps  # Lista os serviços em execução

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
          version: v1.59 
          args: controllers/ database/ models/ routes/

    - name: Check Docker logs
      run: echo "Exibindo logs do Docker..." && docker compose logs

    - name: Test
      run: |
        echo "Aguardando app iniciar..."
        sleep 10
        docker compose exec app go test ./...

    - name: Build
      run: |
         go build main.go

    - name: Compilar projeto
      uses: actions/upload-artifact@v4
      with: 
          name: projeto_compilado 
          path: main

    - name: Upload binary como artefato
      uses: actions/upload-artifact@v4
      with:
        name: go-binary
        path: ./bin/main

